### PR TITLE
Final Draft - Round 1

### LINKED ISSUE #57: Add content to ReadMe
As a team of devs, it will be useful to populate our ReadMe with information relevant to both our audience and client.

To demonstrate the evolution of the site, it would also be helpful to include before and after pics.

### PR DESCRIPTION
**Pull request by brandondombrowsky**
Closer to final; Kristin and I will go over so don't approve PR until we are through the edit process :) 

Resolves #57

### CODE REVIEW

**Review by KristinJJ — APPROVED** [review]
Looks good, thanks for updating the screenshots Brandon!

**Review by KristinJJ — CHANGES_REQUESTED** [review]
Can you also add a link to the Tableau Public Viz in the Readme so it's easier for people to find, just in case they don't see it in the sidebar? Thanks Brandon! https://public.tableau.com/app/profile/kristin.jue/viz/Cranidores470_16837830450670/Story1?publish=yes

**Comment by brandondombrowsky** [comment]
The Tableau Public link is already there :) It is in the Team Proposed Visualizations section as a click "here" option.

**Review by KristinJJ — APPROVED** [review]
Thanks for the reminder, Looks Great To Me Brandon!

**Review by LucasKnezevich — APPROVED** [review]
LGTM

**Pull request merged**
